# Generated by Django 4.1.6 on 2023-06-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='credits',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
