# Generated by Django 4.1.6 on 2023-06-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_products_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='productType',
            field=models.CharField(blank=True, default='Sub', max_length=250, null=True),
        ),
    ]
