# Generated by Django 4.1.6 on 2023-02-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_password_category_details_photo_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='business_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='photo_path',
            field=models.FileField(null=True, upload_to='profile_photo/'),
        ),
    ]
