# Generated by Django 4.1.6 on 2023-03-01 07:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_validation',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
