# Generated by Django 4.1.6 on 2023-03-05 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_validation_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='address_info',
            name='zip_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
