# Generated by Django 4.1.6 on 2023-03-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_password_reset_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='password_manager',
            name='status',
            field=models.BooleanField(default=1),
        ),
    ]
