# Generated by Django 4.1.6 on 2023-04-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_credit_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit_score',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
