# Generated by Django 4.1.6 on 2023-04-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_credit_score_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit_score',
            name='credit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
