# Generated by Django 4.1.6 on 2023-04-06 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_invoice_amount_invoice_product_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='product_purchase',
        ),
    ]
