# Generated by Django 4.1.6 on 2023-06-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_invoice_product_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='photo_path',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photo/'),
        ),
    ]
