# Generated by Django 4.1.6 on 2023-06-02 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_details_photo_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='photo_path',
            new_name='profile_picture',
        ),
    ]
