# Generated by Django 4.1.6 on 2023-06-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_rename_photo_path_details_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='profile_photo/'),
        ),
    ]
