# Generated by Django 4.1.6 on 2023-02-13 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_issue_issue_type_issue_comment_issue_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue_comment',
            old_name='issue_id',
            new_name='issue',
        ),
        migrations.RenameField(
            model_name='issue_comment_file',
            old_name='comment_id',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='issue_file',
            old_name='issue_id',
            new_name='issue',
        ),
        migrations.RenameField(
            model_name='issue_responders',
            old_name='issue_id',
            new_name='issue',
        ),
        migrations.RenameField(
            model_name='task_comment',
            old_name='task_id',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='task_comment_file',
            old_name='comment_id',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='task_responders',
            old_name='task_id',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='tast_file',
            old_name='task_id',
            new_name='task',
        ),
    ]
