# Generated by Django 4.1.6 on 2023-02-13 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_rename_issue_id_issue_comment_issue_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tast_file',
            new_name='task_file',
        ),
    ]
