# Generated by Django 4.1.6 on 2023-03-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_rename_tast_file_task_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
