# Generated by Django 4.1.6 on 2023-05-02 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_issue_create_date_issue_history_issue_update_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='task_cetegory_theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('short_description', models.TextField(null=True)),
                ('is_delete', models.BooleanField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='task_category',
            name='parent',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='task_services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('short_description', models.TextField(null=True)),
                ('is_delete', models.BooleanField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.task_category')),
            ],
        ),
        migrations.AddField(
            model_name='task_category',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.task_cetegory_theme'),
        ),
    ]
