# Generated by Django 4.1.6 on 2023-05-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_task_cetegory_theme_task_category_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_category',
            name='status',
            field=models.BooleanField(default=1),
        ),
    ]
