# Generated by Django 4.1.6 on 2023-05-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_task_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='urgency',
            field=models.CharField(blank=True, default='Low', max_length=250, null=True),
        ),
    ]
