# Generated by Django 4.1.6 on 2023-05-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
