# Generated by Django 4.1.6 on 2023-05-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_task_task_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, default='Open', max_length=250, null=True),
        ),
    ]
