# Generated by Django 4.1.6 on 2023-06-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_issue_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='ticket_status',
            field=models.CharField(blank=True, default='Pending', max_length=250, null=True),
        ),
    ]
