# Generated by Django 4.1.6 on 2023-07-15 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_issue_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='percentage',
            field=models.CharField(blank=True, default=0, max_length=250, null=True),
        ),
    ]
