# Generated by Django 4.1.6 on 2023-07-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_issue_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue_comment_file',
            name='comment_file_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
