# Generated by Django 4.1.6 on 2023-07-18 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_issue_comment_file_comment_file_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue_comment_file',
            old_name='comment',
            new_name='commentId',
        ),
    ]
