# Generated by Django 4.1.6 on 2023-07-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0021_rename_comment_issue_comment_file_commentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_comment_file',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
