# Generated by Django 4.1.6 on 2023-07-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0022_task_comment_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_file',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
