# Generated by Django 4.1.6 on 2023-08-02 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0023_task_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='history',
            field=models.TextField(blank=True, null=True),
        ),
    ]
