# Generated by Django 4.1.6 on 2023-08-02 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0024_task_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='ticket_status',
            field=models.CharField(blank=True, default='Open', max_length=250, null=True),
        ),
    ]
