# Generated by Django 4.1.6 on 2023-08-02 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0025_alter_issue_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='ticket_status',
            field=models.CharField(blank=True, default='OPEN', max_length=250, null=True),
        ),
    ]
