# Generated by Django 4.1.6 on 2023-08-15 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_credit_score_sessionid'),
        ('tickets', '0026_alter_issue_ticket_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='userId',
        ),
        migrations.AddField(
            model_name='issue',
            name='userAccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.details'),
        ),
    ]
