# Generated by Django 4.1.6 on 2023-08-15 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0028_alter_issue_comment_owner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='owner',
            new_name='owner_accountDetails',
        ),
        migrations.RenameField(
            model_name='task_comment',
            old_name='owner',
            new_name='owner_accountDetails',
        ),
        migrations.RenameField(
            model_name='task_responders',
            old_name='responder',
            new_name='owner_accountDetails',
        ),
    ]
