# Generated by Django 4.1.6 on 2023-08-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0031_task_comment_file_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_comment',
            name='is_private',
            field=models.BooleanField(default=0),
        ),
    ]
