# Generated by Django 4.1.6 on 2023-08-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0033_task_services_parent_alter_task_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, default='OPEN', max_length=250, null=True),
        ),
    ]
