# Generated by Django 4.1.6 on 2023-08-25 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0034_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='severity',
            field=models.TextField(blank=True, default='LOW', max_length=250, null=True),
        ),
    ]
