# Generated by Django 4.1.6 on 2023-08-25 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0035_issue_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='ticket_prev_status',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
