# Generated by Django 4.1.6 on 2023-08-25 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_credit_score_sessionid'),
        ('tickets', '0036_issue_ticket_prev_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='ticket_prev_status',
        ),
        migrations.CreateModel(
            name='issue_trail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_prev_status', models.CharField(blank=True, max_length=250, null=True)),
                ('userAccount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.details')),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='trail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.issue_trail'),
        ),
    ]
