# Generated by Django 4.1.6 on 2023-08-25 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_credit_score_sessionid'),
        ('tickets', '0037_remove_issue_ticket_prev_status_issue_trail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='trail',
        ),
        migrations.AddField(
            model_name='issue',
            name='user_last_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_person_to_update_the_ticket', to='accounts.details'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='userAccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_owner', to='accounts.details'),
        ),
        migrations.DeleteModel(
            name='issue_trail',
        ),
    ]
