# Generated by Django 4.1.6 on 2023-08-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0038_remove_issue_trail_issue_user_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='severity',
            field=models.CharField(blank=True, default='LOW', max_length=250, null=True),
        ),
    ]
