# Generated by Django 4.1.6 on 2023-08-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0039_alter_issue_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue_comment',
            name='is_private',
            field=models.BooleanField(default=0),
        ),
    ]
