# Generated by Django 4.1.6 on 2023-08-29 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_credit_score_sessionid'),
        ('tickets', '0041_issue_comment_file_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user_last_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_person_to_update_the_task', to='accounts.details'),
        ),
        migrations.AlterField(
            model_name='task',
            name='urgency',
            field=models.CharField(blank=True, default='LOW', max_length=250, null=True),
        ),
    ]
