# Generated by Django 4.1.6 on 2023-09-07 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0042_task_user_last_updated_alter_task_urgency'),
    ]

    operations = [
        migrations.CreateModel(
            name='task_sub_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('short_description', models.TextField(null=True)),
                ('status', models.BooleanField(default=1)),
                ('is_delete', models.BooleanField(default=0)),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.task_category')),
            ],
        ),
        migrations.CreateModel(
            name='task_services_sub_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('short_description', models.TextField(null=True)),
                ('is_delete', models.BooleanField(default=0)),
                ('services', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.task_services')),
            ],
        ),
        migrations.AlterField(
            model_name='task_services',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.task_sub_category'),
        ),
    ]
