# Generated by Django 4.1.6 on 2023-09-11 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0043_task_sub_category_task_services_sub_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task_sub_category',
            old_name='theme',
            new_name='category',
        ),
    ]
