# Generated by Django 4.1.6 on 2023-09-11 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0044_rename_theme_task_sub_category_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task_services',
            old_name='category',
            new_name='sub_category',
        ),
    ]
