# Generated by Django 4.1.6 on 2023-09-11 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0045_rename_category_task_services_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_cetegory_theme',
            name='active',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='task_cetegory_theme',
            name='introduction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task_cetegory_theme',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task_cetegory_theme',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='category_assistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assitance', models.TextField(blank=True, null=True)),
                ('is_delete', models.BooleanField(default=0)),
                ('category_theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.task_cetegory_theme')),
            ],
        ),
    ]
