# Generated by Django 4.1.6 on 2023-09-12 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0046_task_cetegory_theme_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category_assistance',
            old_name='assitance',
            new_name='assistance',
        ),
    ]
