# Generated by Django 4.1.6 on 2023-09-12 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0047_rename_assitance_category_assistance_assistance'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_category',
            name='introduction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task_category',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task_category',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
