# Generated by Django 4.1.6 on 2023-09-14 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0048_task_category_introduction_task_category_overview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='category_feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.BooleanField(default=1)),
                ('is_delete', models.BooleanField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.task_category')),
            ],
        ),
    ]
