# Generated by Django 4.1.6 on 2023-09-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0049_category_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_feature',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
