# Generated by Django 4.1.6 on 2023-09-16 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0050_alter_category_feature_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_services',
            name='status',
            field=models.BooleanField(default=1),
        ),
    ]
