# Generated by Django 4.1.6 on 2023-09-18 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0051_task_services_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_sub_category',
            name='introduction',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='task_sub_category',
            name='overview',
            field=models.TextField(null=True),
        ),
    ]
