# Generated by Django 4.1.6 on 2023-09-18 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0052_task_sub_category_introduction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_services',
            name='introduction',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='task_services',
            name='overview',
            field=models.TextField(null=True),
        ),
    ]
