# Generated by Django 4.1.6 on 2023-09-18 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0053_task_services_introduction_task_services_overview'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_services_sub_type',
            name='introduction',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='task_services_sub_type',
            name='overview',
            field=models.TextField(null=True),
        ),
    ]
